.TH NOVPROG "1" "January 2015"

.SH "NAME"
novprog \- wordcount graphing program

.SH "SYNOPSIS"
.PP
.B novprog

.SH "DESCRIPTION"
.PP
\fINovProg\fR is a tool to graph your progress in writing a NaNoWriMo style
novel. You enter your wordcount and it updates a graph showing you how much
progress you have made. It also shows you how far you are through your
daily goal, and your total goal. Mousing over a bar in the graph will show
a tooltip with that day's wordcount.

.SH "COPYRIGHT"
.PP
Copyright \(co 2015 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
