.TH NOVPROG 1 "January 2025" "NovProg 3.2.4" "General Commands Manual"

.SH "NAME"
novprog \- wordcount graphing program

.SH "SYNOPSIS"
.B novprog
[options]

.SH "DESCRIPTION"
NovProg is a tool to graph your progress in writing a NaNoWriMo style
novel. You enter your wordcount and it updates a graph showing you how much
progress you have made. It also shows you how far you are through your
daily goal, and your total goal. Mousing over a bar in the graph will show
a tooltip with that day's wordcount.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.

.SH "SEE ALSO"
.BR qt6options (7)

.SH "REPORTING BUGS"
Report bugs to <novprog@bugs.gottcode.org>.

.SH "COPYRIGHT"
Copyright \(co 2006-2025 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
Graeme Gott <graeme@gottcode.org>.
